language: java
jdk:
  - oraclejdk8
sudo: true

script:
  - mvn clean package

notifications:
  slack:
    rooms:
      - p632:20oR0X45QVtC9RACNHghchWR
    on_success: change
    on_failure: always

addons:
  code_climate:
    repo_token: 8860173d24d4bee5353db985c3ef17bdfbf06ca038474f8b0b9f883410f32561

after_script:
   - npm install -g codeclimate-test-reporter
   - codeclimate-test-reporter < lcov.info
