language: java
jdk:
  - oraclejdk8
sudo: true

script:
  - mvn test

notifications:
  slack: 
    rooms: 
      - p632:20oR0X45QVtC9RACNHghchWR
    on_success: change
    on_failure: always

# addons:
#   code_climate:
#     repo_token:
#
# after_script:
#    codeclimate-test-reporter < lcov.info
